name: elephant

library:
  source-dirs: lib
  exposed-modules:
    - Elephant

dependencies:
  - base
  - microlens
  - microlens-mtl
  - mtl
  - transformers

ghc-options:
  - -Wall

tests:
  doctest:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
      - elephant
